name: Sync Github Repo to AWS CodeCommit Action
description: 'Synchronize your GitHub Repository to AWS CodeCommit via Github Actions. You only need an AWS IAM Credentials on your steps.'
author: 'mamaoag'
branding:
  icon: upload-cloud
  color: orange
inputs:
  repository_name:
    description: AWS CodeCommit repository name.
    required: true
  aws_region:
    description: Region of the CodeCommit repository.
    required: true
runs:
  using: 'docker'
  image: './Dockerfile'
